#! /bin/bash
input="../Player_Analysis/Roulette_Losses.txt"
while IFS= read -r line; do
#echo "$line" ;
date=$(echo $line | awk -F" " '{print $1}');
tod=$(echo $line | awk -F" " '{print $2" "$3}') ;
whichsched=$(echo $line | awk -F" " '{print $1"_Dealer_schedule"}') ;
whathour=$(echo $line | awk -F" " '{print $2}' );
amorpm=$(echo $line | awk -F" " '{print $3}');
dealer=$(grep $whathour $whichsched | grep $amorpm | awk -F" " '{print  $5" "$6}') ;
#echo "echo "$dealer > "whowasroulettedealerat"$date$whathour$amorpm.sh;
echo "
#! /bin/bash
date="$date";
whichsched="$whichsched" ;
whathour="$whathour";
amorpm="$amorpm";
dealer=\$(grep $whathour $whichsched | grep $amorpm | awk '{print \$5\" \"\$6}') ; echo \$dealer;"> "whowasroulettedealerat"$date$whathour$amorpm.sh;
chmod +x "whowasroulettedealerat"$date$whathour$amorpm.sh;
done < $input
